/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNewsletterRouteImport } from './routes/dashboard/newsletter'
import { Route as DashboardDonationsRouteImport } from './routes/dashboard/donations'
import { Route as DashboardDonationConfirmationTemplateRouteImport } from './routes/dashboard/donation-confirmation-template'

const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewsletterRoute = DashboardNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDonationsRoute = DashboardDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDonationConfirmationTemplateRoute =
  DashboardDonationConfirmationTemplateRouteImport.update({
    id: '/donation-confirmation-template',
    path: '/donation-confirmation-template',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donate': typeof DonateRoute
  '/facebook': typeof FacebookRoute
  '/instagram': typeof InstagramRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRoute
  '/dashboard/donation-confirmation-template': typeof DashboardDonationConfirmationTemplateRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/newsletter': typeof DashboardNewsletterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/facebook': typeof FacebookRoute
  '/instagram': typeof InstagramRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRoute
  '/dashboard/donation-confirmation-template': typeof DashboardDonationConfirmationTemplateRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/newsletter': typeof DashboardNewsletterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donate': typeof DonateRoute
  '/facebook': typeof FacebookRoute
  '/instagram': typeof InstagramRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRoute
  '/dashboard/donation-confirmation-template': typeof DashboardDonationConfirmationTemplateRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/newsletter': typeof DashboardNewsletterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/donate'
    | '/facebook'
    | '/instagram'
    | '/login'
    | '/priorities'
    | '/dashboard/donation-confirmation-template'
    | '/dashboard/donations'
    | '/dashboard/newsletter'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/facebook'
    | '/instagram'
    | '/login'
    | '/priorities'
    | '/dashboard/donation-confirmation-template'
    | '/dashboard/donations'
    | '/dashboard/newsletter'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/donate'
    | '/facebook'
    | '/instagram'
    | '/login'
    | '/priorities'
    | '/dashboard/donation-confirmation-template'
    | '/dashboard/donations'
    | '/dashboard/newsletter'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DonateRoute: typeof DonateRoute
  FacebookRoute: typeof FacebookRoute
  InstagramRoute: typeof InstagramRoute
  LoginRoute: typeof LoginRoute
  PrioritiesRoute: typeof PrioritiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletter': {
      id: '/dashboard/newsletter'
      path: '/newsletter'
      fullPath: '/dashboard/newsletter'
      preLoaderRoute: typeof DashboardNewsletterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/donations': {
      id: '/dashboard/donations'
      path: '/donations'
      fullPath: '/dashboard/donations'
      preLoaderRoute: typeof DashboardDonationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/donation-confirmation-template': {
      id: '/dashboard/donation-confirmation-template'
      path: '/donation-confirmation-template'
      fullPath: '/dashboard/donation-confirmation-template'
      preLoaderRoute: typeof DashboardDonationConfirmationTemplateRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDonationConfirmationTemplateRoute: typeof DashboardDonationConfirmationTemplateRoute
  DashboardDonationsRoute: typeof DashboardDonationsRoute
  DashboardNewsletterRoute: typeof DashboardNewsletterRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDonationConfirmationTemplateRoute:
    DashboardDonationConfirmationTemplateRoute,
  DashboardDonationsRoute: DashboardDonationsRoute,
  DashboardNewsletterRoute: DashboardNewsletterRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DonateRoute: DonateRoute,
  FacebookRoute: FacebookRoute,
  InstagramRoute: InstagramRoute,
  LoginRoute: LoginRoute,
  PrioritiesRoute: PrioritiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
